### PR TITLE
Add support for account capabilities

### PR DESCRIPTION
**Pull request by cketti**

### CODE REVIEW

**Comment by iNPUTmice** [comment]
Huh, interesting. I hadn’t noticed that the protocol had changed in that regard. Anyway thanks for spotting and fixing that.

A couple of notes.

This PR copies the CapabilitySerializer that is neither tested nor used. I think it was one of the first custom (de)serializers I wrote when I hadn’t decided to (for now) focus on the client side of things. However that is solely an oversight on my part that this PR shouldn’t mimic. I think the (Account)CapabilitySerializer should either be removed or unit tested. Mid term I would prefer that latter but I'd be willing to merge this PR with the serializer removed instead of tested.

(Actually the Deserializer for both Capability and AccountCapabiltiy could use a unit test as well.)

**Comment by cketti** [comment]
It looks like `SessionFileCache` uses Gson to serialize `Session`. Via `SessionResource` this leads to needing to serialize `Capability` and `AccountCapabiltiy`.

**Comment by cketti** [comment]
I added tests for `AccountCapabilitiesDeserializer` and `AccountCapabilitiesSerializer`.

**Comment by iNPUTmice** [comment]
Thank you for adding those tests.

I was thinking that we can maybe use `@Getter` and `@Builder` instead of a public constructor for the Capabilities. That would be more in line with the rest of the Pojos in `jmap-common`.

**Comment by cketti** [comment]
Done. I also added `@ToString` which makes for a nicer debugging experience.

**Pull request merged**
